package com.bobfull.common.monitoring;

// Prometheus label cardinality를 제한하는 비즈니스 사건 이름 집합이다.
public enum BusinessMetricEvent {
    PAYMENT_COMPENSATION_REQUIRED,
    REFUND_COMPENSATION_REQUIRED,
    PORTONE_WEBHOOK_PROCESSING_FAILED,
    CHAT_ROOM_CREATION_REQUIRED,
    UNHANDLED_EXCEPTION,
    LOGIN_FAILED,
    AUTH_REISSUE_FAILED,
    IMAGE_STORAGE_REQUEST_FAILED,
    RECRUITMENT_DEADLINE_FAILED,
    PAYMENT_WEBHOOK_PERMANENT_FAILURE,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLATION_COMPLETED,
    PAYMENT_COMPLETED,
    READY_PAYMENT_EXPIRED,
    REFUND_COMPLETED,
    NO_SHOW_MARKED,
    CHAT_MODERATION_RETRY_EXHAUSTED,
    RESTAURANT_INSIGHT_RETRY_EXHAUSTED,
    CHAT_REALTIME_PUBLISH_FAILED,
    CHAT_REALTIME_SUBSCRIBE_FAILED
}
