package com.bobfull.chat.application.service;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.BDDMockito.*;
import com.bobfull.chat.presentation.dto.*; import com.bobfull.chat.domain.entity.*; import com.bobfull.chat.infrastructure.repository.*; import com.bobfull.common.exception.*; import com.bobfull.reservation.infrastructure.repository.ReservationParticipantRepository; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.test.util.ReflectionTestUtils;
class ChatRoomMemberReportServiceTest {
 private final ChatRoomRepository rooms=mock(ChatRoomRepository.class); private final ChatMessageRepository messages=mock(ChatMessageRepository.class); private final ChatRoomMemberReportRepository reports=mock(ChatRoomMemberReportRepository.class); private final ReservationParticipantRepository participants=mock(ReservationParticipantRepository.class); private final ChatRoomMemberReportService service=new ChatRoomMemberReportService(rooms,messages,reports,participants);
 @Test void JWT_신고자와_같은방_참여이력이_있으면_신고를_생성한다(){ChatRoom room=room(3L,10L); given(rooms.findById(3L)).willReturn(Optional.of(room));given(participants.existsByReservationIdAndMemberId(10L,7L)).willReturn(true);given(participants.existsByReservationIdAndMemberId(10L,8L)).willReturn(true);given(reports.save(any())).willAnswer(i->{ChatRoomMemberReport r=i.getArgument(0);ReflectionTestUtils.setField(r,"id",99L);return r;});assertThat(service.create(7L,3L,8L,new ChatRoomMemberReportCreateRequest(ReportReason.ABUSE,null,null)).reporterMemberId()).isEqualTo(7L);}
 @Test void 다른방_anchor와_같은대상_중복_신고를_차단한다(){ChatRoom room=room(3L,10L);given(rooms.findById(3L)).willReturn(Optional.of(room));given(participants.existsByReservationIdAndMemberId(anyLong(),anyLong())).willReturn(true);given(reports.existsByReporterMemberIdAndChatRoomIdAndReportedMemberId(7L,3L,8L)).willReturn(true);assertThatThrownBy(()->service.create(7L,3L,8L,new ChatRoomMemberReportCreateRequest(ReportReason.ABUSE,11L,null))).isInstanceOf(CustomException.class).extracting(e->((CustomException)e).getErrorCode()).isEqualTo(ChatErrorCode.CHAT_ROOM_REPORT_DUPLICATE);}
 @Test void 자기신고와_OTHER_상세누락과_비참여자를_차단한다(){given(rooms.findById(3L)).willReturn(Optional.of(room(3L,10L)));assertThatThrownBy(()->service.create(7L,3L,7L,new ChatRoomMemberReportCreateRequest(ReportReason.ABUSE,null,null))).isInstanceOf(CustomException.class);assertThatThrownBy(()->service.create(7L,3L,8L,new ChatRoomMemberReportCreateRequest(ReportReason.OTHER,null," "))).isInstanceOf(CustomException.class);given(participants.existsByReservationIdAndMemberId(10L,7L)).willReturn(true);given(participants.existsByReservationIdAndMemberId(10L,8L)).willReturn(false);assertThatThrownBy(()->service.create(7L,3L,8L,new ChatRoomMemberReportCreateRequest(ReportReason.ABUSE,null,null))).isInstanceOf(CustomException.class);}
 @Test void 다른방이나_다른작성자_anchor를_차단한다(){given(rooms.findById(3L)).willReturn(Optional.of(room(3L,10L)));given(participants.existsByReservationIdAndMemberId(anyLong(),anyLong())).willReturn(true);ChatMessage m=ChatMessage.create(4L,8L,1L,"x");ReflectionTestUtils.setField(m,"id",11L);given(messages.findById(11L)).willReturn(Optional.of(m));assertThatThrownBy(()->service.create(7L,3L,8L,new ChatRoomMemberReportCreateRequest(ReportReason.ABUSE,11L,null))).isInstanceOf(CustomException.class);}
 private ChatRoom room(Long id,Long reservation){ChatRoom r=ChatRoom.create(reservation);ReflectionTestUtils.setField(r,"id",id);return r;}
}
