package com.bobfull.chat.infrastructure.ai;

import static org.assertj.core.api.Assertions.assertThat;
import com.bobfull.chat.application.dto.ModerationResult; import com.bobfull.chat.domain.entity.*; import java.util.*; import org.junit.jupiter.api.Tag; import org.junit.jupiter.api.Test; import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable; import org.springframework.ai.chat.client.ChatClient; import org.springframework.ai.chat.client.ResponseEntity; import org.springframework.ai.chat.model.ChatResponse; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource;

/** #218 Scope 계약 전용 실제 Provider Regression이다. 기존 v2 40건 평가와 독립적으로 유지한다. */
@Tag("openai-evaluation") @EnabledIfEnvironmentVariable(named="OPENAI_API_KEY",matches=".+") @ActiveProfiles("local")
@SpringBootTest(properties={"spring.ai.openai.chat.model=${OPENAI_EVAL_MODEL:${OPENAI_CHAT_MODEL:gpt-4o-mini}}","spring.datasource.url=jdbc:h2:mem:openai-v3-scope;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1","spring.datasource.username=sa","spring.datasource.password=","spring.datasource.driver-class-name=org.h2.Driver","spring.jpa.hibernate.ddl-auto=create-drop","jwt.secret=openai-evaluation-only-secret-key-with-minimum-length","portone.api-secret=test-api-secret","portone.store-id=test-store-id","portone.webhook-secret=d2hzZWNfZEdWemRDMXpkR055WlhRPQ==","spring.mail.host=localhost","spring.mail.port=1025","payment.expiration.enabled=false","payment.refund-reconciliation.enabled=false","reservation.recruitment-deadline.enabled=false","reservation.dining-end.enabled=false","outbox.chat-room.enabled=false","outbox.email.enabled=false"})
class SpringAiModerationV3ScopeRegressionTest {
 @Autowired @Qualifier("moderationChatClient") ChatClient client; @Value("${spring.ai.openai.chat.model}") String model; @Value("${bobfull.ai.moderation.max-output-tokens}") int maxTokens;
 @DynamicPropertySource static void key(DynamicPropertyRegistry r){r.add("spring.ai.openai.api-key",()->System.getenv("OPENAI_API_KEY"));}
 @Test void Issue218_v3_scope_고정_12건을_실제_OpenAI로_기록한다(){assertThat(ModerationPrompt.PROMPT_VERSION).isEqualTo("moderation-prompt-v3-scope");assertThat(ModerationPrompt.POLICY_VERSION).isEqualTo("moderation-policy-v2");for(Case c:cases()){ModerationResult a=call(c.input());boolean pass=a.result()==c.result()&&a.categories().equals(c.categories())&&a.riskLevel()==c.risk();System.out.printf("[V3-SCOPE] id=%s input=%s expected=%s/%s/%s actual=%s/%s/%s %s%n",c.id(),c.input(),c.result(),c.categories(),c.risk(),a.result(),a.categories(),a.riskLevel(),pass?"PASS":"FAIL");assertThat(a.result()).isEqualTo(c.result());assertThat(a.categories()).isEqualTo(c.categories());assertThat(a.riskLevel()).isEqualTo(c.risk());}}
 private ModerationResult call(String input){ResponseEntity<ChatResponse,ModerationResult> r=client.prompt().system(ModerationPrompt.SYSTEM_PROMPT).user(input).options(OpenAiModerationEvaluationOptions.forModel(model,maxTokens)).call().responseEntity(ModerationResult.class,s->s.useProviderStructuredOutput());return r.entity();}
 private static List<Case> cases(){return List.of(s("V3-SAFE-01","바보야"),s("V3-SAFE-02","ㅋㅋ 이 멍청아"),s("V3-SAFE-03","식당 전화번호는 02-1234-5678입니다"),s("V3-SAFE-04","맛집 지도 링크입니다 https://map.example"),f("V3-PROFANITY-01","개새끼야",ModerationCategory.PROFANITY,RiskLevel.HIGH),f("V3-PROFANITY-02","죽여버린다",ModerationCategory.PROFANITY,RiskLevel.HIGH),f("V3-PI-01","내 번호 010-1234-5678이야",ModerationCategory.PERSONAL_INFORMATION,RiskLevel.MEDIUM),f("V3-PI-02","제 이메일은 minsu@example.com입니다",ModerationCategory.PERSONAL_INFORMATION,RiskLevel.MEDIUM),f("V3-PI-03","계좌번호 123-456-789012로 보내 주세요",ModerationCategory.PERSONAL_INFORMATION,RiskLevel.MEDIUM),f("V3-SPAM-01","코인 수익방 들어오세요",ModerationCategory.SPAM,RiskLevel.HIGH),f("V3-SPAM-02","추천코드 입력하면 할인 쿠폰 드려요",ModerationCategory.SPAM,RiskLevel.MEDIUM),f("V3-SPAM-03","VIP 투자방 멤버를 모집합니다",ModerationCategory.SPAM,RiskLevel.HIGH));}
 private static Case s(String id,String input){return new Case(id,input,ModerationResultType.SAFE,Set.of(),RiskLevel.LOW);} private static Case f(String id,String input,ModerationCategory category,RiskLevel risk){return new Case(id,input,ModerationResultType.FLAGGED,Set.of(category),risk);} private record Case(String id,String input,ModerationResultType result,Set<ModerationCategory> categories,RiskLevel risk){}
}
