package com.bobfull.restaurantinsight.domain.entity;
public enum FeedbackOpinionType {
    TASTE, TEXTURE, SALTINESS, SPICINESS, SWEETNESS, PORTION, FRESHNESS, TEMPERATURE,
    FRIENDLINESS, SERVICE_SPEED, PRICE_LEVEL, CLEANLINESS, WAITING, ETC
}
